# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AnsiblePlaybookSample:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: ansible-playbook-sample
      Description: This is a sample component that demonstrates how to download and execute an Ansible playbook against Amazon Linux 2.
      Platform: Linux
      Version: '1.0.0'
      Data: |
        name: 'Ansible Playbook Execution on Amazon Linux 2'
        description: 'This is a sample component that demonstrates how to download and execute an Ansible playbook against Amazon Linux 2.'
        schemaVersion: 1.0
        phases:
          - name: build
            steps:
              - name: InstallAnsible
                action: ExecuteBash
                inputs:
                  commands:
                  - sudo amazon-linux-extras install -y ansible2
              - name: InstallGit
                action: ExecuteBash
                inputs:
                  commands:
                  - sudo yum install -y git
              - name: Test
                action: ExecuteBash
                inputs:
                  commands:
                  - |
                    set -x
                    sudo su -l ec2-user -c '(
                    t=$(mktemp -d)
                    git clone --recurse-submodules https://github.com/whslabs/packer-cardano-node.git $t
                    cd $t/ansible/
                    ansible-playbook -idefault, -clocal playbook.yaml
                    )'
          # - name: validate
          #   steps:
          #     - name: ValidateResponse
          #       action: ExecuteBash
          #       inputs:
          #         commands:
          #           - true
          # - name: test
          #   steps:
          #     - name: ValidateResponse
          #       action: ExecuteBash
          #       inputs:
          #         commands:
          #           - true
